// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpODVoSRwSDJYH-qhpQcwTaSSnMccAvxU',
    appId: '1:314833789537:web:1dfa8b7c98d6d492310020',
    messagingSenderId: '314833789537',
    projectId: 'bisonhacks-chatbot-3083e',
    authDomain: 'bisonhacks-chatbot-3083e.firebaseapp.com',
    storageBucket: 'bisonhacks-chatbot-3083e.appspot.com',
    measurementId: 'G-BNT7PYZJQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiPYB3wQF8Bui8G_UomVItSxqm-M4rlrk',
    appId: '1:314833789537:android:929d5d4042336120310020',
    messagingSenderId: '314833789537',
    projectId: 'bisonhacks-chatbot-3083e',
    storageBucket: 'bisonhacks-chatbot-3083e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSjGTZZMnP1AoUxn9TkLPuBiCC1Twu0T0',
    appId: '1:314833789537:ios:63fb719576c4e289310020',
    messagingSenderId: '314833789537',
    projectId: 'bisonhacks-chatbot-3083e',
    storageBucket: 'bisonhacks-chatbot-3083e.appspot.com',
    iosBundleId: 'com.example.hsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSjGTZZMnP1AoUxn9TkLPuBiCC1Twu0T0',
    appId: '1:314833789537:ios:63fb719576c4e289310020',
    messagingSenderId: '314833789537',
    projectId: 'bisonhacks-chatbot-3083e',
    storageBucket: 'bisonhacks-chatbot-3083e.appspot.com',
    iosBundleId: 'com.example.hsg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpODVoSRwSDJYH-qhpQcwTaSSnMccAvxU',
    appId: '1:314833789537:web:5fdfd0aecb5a3cd4310020',
    messagingSenderId: '314833789537',
    projectId: 'bisonhacks-chatbot-3083e',
    authDomain: 'bisonhacks-chatbot-3083e.firebaseapp.com',
    storageBucket: 'bisonhacks-chatbot-3083e.appspot.com',
    measurementId: 'G-FNBY8JBFD0',
  );
}
